image:
  name: docker:latest

services:
  - docker:dind

before_script:
  - apk add curl

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker compose -f compose.yaml -f compose.php.yaml build --pull
    - docker tag app-php $CI_REGISTRY_IMAGE/app-php:latest
    - docker push $CI_REGISTRY_IMAGE/app-php:latest
  when: manual


test-job:
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - IMAGES_PREFIX="$CI_REGISTRY_IMAGE/" docker compose -f compose.yaml -f compose.php.yaml -f compose.test.yaml up --wait --no-build
    - docker compose exec -T php echo $APP_DEV
    - docker compose exec php php bin/console oro:install --env=test
    - docker compose exec -T php bin/phpunit vendor/oro/commerce/src/Oro/Bundle/ProductBundle/Tests/Unit
    - docker compose exec -T php bin/phpunit vendor/oro/commerce/src/Oro/Bundle/ProductBundle/Tests/Functional
