services:
  database:
    image: oroinc/pgsql:15.3-alpine
    ports: ["5432"]
    labels:
      com.symfony.server.service-prefix: 'ORO_DB'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-oro_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-oro_db_pass}
      POSTGRES_USER: ${POSTGRES_USER:-oro_db_user}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  redis:
    labels:
      com.symfony.server.service-prefix: 'ORO_REDIS'
    image: redis:6-alpine
    ports: ["6379"]

volumes:
    database_data:
